# permissions for end users to edit databaseusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: databaseuser-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: external-database-operator
    app.kubernetes.io/part-of: external-database-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseuser-editor-role
rules:
- apiGroups:
  - postgresql.my.domain
  resources:
  - databaseusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.my.domain
  resources:
  - databaseusers/status
  verbs:
  - get
